/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RcaRouteImport } from './routes/rca'
import { Route as PublicSafetyRouteImport } from './routes/public-safety'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CyberResilienceRouteImport } from './routes/cyber-resilience'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RcaRoute = RcaRouteImport.update({
  id: '/rca',
  path: '/rca',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSafetyRoute = PublicSafetyRouteImport.update({
  id: '/public-safety',
  path: '/public-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberResilienceRoute = CyberResilienceRouteImport.update({
  id: '/cyber-resilience',
  path: '/cyber-resilience',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/cyber-resilience': typeof CyberResilienceRoute
  '/documents': typeof DocumentsRoute
  '/experts': typeof ExpertsRoute
  '/graph': typeof GraphRoute
  '/lessons': typeof LessonsRoute
  '/maintenance': typeof MaintenanceRoute
  '/public-safety': typeof PublicSafetyRoute
  '/rca': typeof RcaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/cyber-resilience': typeof CyberResilienceRoute
  '/documents': typeof DocumentsRoute
  '/experts': typeof ExpertsRoute
  '/graph': typeof GraphRoute
  '/lessons': typeof LessonsRoute
  '/maintenance': typeof MaintenanceRoute
  '/public-safety': typeof PublicSafetyRoute
  '/rca': typeof RcaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/cyber-resilience': typeof CyberResilienceRoute
  '/documents': typeof DocumentsRoute
  '/experts': typeof ExpertsRoute
  '/graph': typeof GraphRoute
  '/lessons': typeof LessonsRoute
  '/maintenance': typeof MaintenanceRoute
  '/public-safety': typeof PublicSafetyRoute
  '/rca': typeof RcaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/compliance'
    | '/copilot'
    | '/cyber-resilience'
    | '/documents'
    | '/experts'
    | '/graph'
    | '/lessons'
    | '/maintenance'
    | '/public-safety'
    | '/rca'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/compliance'
    | '/copilot'
    | '/cyber-resilience'
    | '/documents'
    | '/experts'
    | '/graph'
    | '/lessons'
    | '/maintenance'
    | '/public-safety'
    | '/rca'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/compliance'
    | '/copilot'
    | '/cyber-resilience'
    | '/documents'
    | '/experts'
    | '/graph'
    | '/lessons'
    | '/maintenance'
    | '/public-safety'
    | '/rca'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  CyberResilienceRoute: typeof CyberResilienceRoute
  DocumentsRoute: typeof DocumentsRoute
  ExpertsRoute: typeof ExpertsRoute
  GraphRoute: typeof GraphRoute
  LessonsRoute: typeof LessonsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PublicSafetyRoute: typeof PublicSafetyRoute
  RcaRoute: typeof RcaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rca': {
      id: '/rca'
      path: '/rca'
      fullPath: '/rca'
      preLoaderRoute: typeof RcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-safety': {
      id: '/public-safety'
      path: '/public-safety'
      fullPath: '/public-safety'
      preLoaderRoute: typeof PublicSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-resilience': {
      id: '/cyber-resilience'
      path: '/cyber-resilience'
      fullPath: '/cyber-resilience'
      preLoaderRoute: typeof CyberResilienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  CyberResilienceRoute: CyberResilienceRoute,
  DocumentsRoute: DocumentsRoute,
  ExpertsRoute: ExpertsRoute,
  GraphRoute: GraphRoute,
  LessonsRoute: LessonsRoute,
  MaintenanceRoute: MaintenanceRoute,
  PublicSafetyRoute: PublicSafetyRoute,
  RcaRoute: RcaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
